flatpak install flathub org.mozilla.firefox
flatpak install flathub org.videolan.VLC
flatpak install flathub com.discordapp.Discord
flatpak install flathub com.github.micahflee.torbrowser-launcher
flatpak install flathub com.visualstudio.code
flatpak install flathub md.obsidian.Obsidian
flatpak install flathub org.kde.kdenlive
flatpak install flathub org.inkscape.Inkscape
flatpak install flathub org.blender.Blender
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub com.nextcloud.desktopclient.nextcloud
flatpak install flathub org.signal.Signal
flatpak install flathub com.github.johnfactotum.Foliate
flatpak install flathub io.github.Figma_Linux.figma_linux
flatpak install flathub org.qbittorrent.qBittorrent
flatpak install flathub io.github.seadve.Kooha
flatpak install flathub io.mpv.Mpv
flatpak install flathub org.gnu.emacs
flatpak install flathub org.gimp.GIMP
flatpak install flathub org.keepassxc.KeePassXC
flatpak install flathub com.rafaelmardojai.Blanket
flatpak install flathub org.xonotic.Xonotic
flatpak install flathub com.sublimetext.three
flatpak install flathub com.simplenote.Simplenote
flatpak install flathub com.getmailspring.Mailspring
flatpak install flathub org.gnome.DejaDup
