#!/bin/bash
#my apps that need to be installed
sudo apt install vlc gnome-tweaks snapd 
 sudo snap install discord simplenote notion-snap  mailspring 
sudo sanp install --classic code
sudo add-apt-repository ppa:agornostal/ulauncher 
 sudo apt update  sudo apt install ulauncher 
sudo apt install ./ulauncher_x.y.z_all.deb 
echo "echo deb http://repo.vivaldi.com/stable/deb/ stable main > /etc/apt/sources.list.d/vivaldi.list" | sudo sh
curl http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551

sudo apt-get install vivaldi-stable  
sudo snap install chromium  
sudo snap install spotify
